FROM vlog-automation-asr:latest
RUN pip3 install --break-system-packages --no-cache-dir --no-deps torchvision --index-url https://download.pytorch.org/whl/cu128
RUN pip3 install --break-system-packages --no-cache-dir qwen-vl-utils==0.0.14 bitsandbytes
WORKDIR /worker
COPY app ./app
CMD ["python3", "-m", "app.visual_worker"]
